Disable ruby-head build because of bundler error
$ gem query --local | grep bundler >/dev/null || gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such
name (https://rubygems.org/latest_specs.4.8.gz)
The command "gem install bundler" failed and exited with 2 during setup.
Your build has been stopped.

See https://github.com/travis-ci/travis-ci/issues/1195.